pipeline {
    agent 'any'
    stages {
        stage('prepare') {
            steps {
                script {
                    println "project_name: ${project_name}"
                    println "code_dir: ${code_dir}"
                    println "server_ip_address: ${server_ip_address}"
                    println "server_hostname: ${server_hostname}"
                    println "build_variant: ${build_variant}"
                    println "build_sign: ${build_sign}"
                    println "build_action: ${build_action}"
                    println "build_verity: ${build_verity}"
                    println "need_publish: ${need_publish}"
                    println "devops_host_id: ${devops_host_id}"
                    println "devops_compile_id: ${devops_compile_id}"
                    println "is_new_project: ${is_new_project}"
                    println "test_pipeline: ${test_pipeline}"
                    println "test_host: ${test_host}"
                    println "sign_ftp_url: ${sign_ftp_url}"
                    println "sign_ftp_upload_username: ${sign_ftp_upload_username}"
                    println "sign_ftp_upload_passwd: ${sign_ftp_upload_passwd}"
                    println "sv_platform_url: ${sv_platform_url}"
                    println "sv_platform_username: ${sv_platform_username}"
                    println "sv_platform_passwd: ${sv_platform_passwd}"
                    println "sv_platform_terrace: ${sv_platform_terrace}"
                    println "sv_platform_board: ${sv_platform_board}"
                    println "sv_platform_model: ${sv_platform_model}"
                    println "sv_platform_brand: ${sv_platform_brand}"
                    println "sv_platform_odm: ${sv_platform_odm}"
                    println "sv_platform_cclist: ${sv_platform_cclist}"
                    println "sv_verity_purpose: ${sv_verity_purpose}"
                    println "publish_username: ${publish_username}"
                    println "LOCAL_SCRIPT_PATH: ${LOCAL_SCRIPT_PATH}"
                    println "REMOTE_SCRIPT_PATH: ${REMOTE_SCRIPT_PATH}"
                }
            }
        }
        stage('prepare-jenkins-server') {
            steps {
                script {
                    sh '''
                    if ! type sshpass >/dev/null 2>&1; then
                        echo -e "\nprepare-jenkins-server: install sshpass"
                        if type apt-get >/dev/null 2>&1; then
                            sudo -S apt-get install sshpass -y << EOF
1
EOF
                        elif type yum >/dev/null 2>&1; then
                            yum install sshpass -y
                        fi
                    fi
                    if ! type pip3 >/dev/null 2>&1; then
                        echo -e "\nprepare-jenkins-server: install python3-pip"
                        if type apt-get >/dev/null 2>&1; then
                            sudo -S apt-get install python3-pip -y << EOF
1
EOF
                        elif type yum >/dev/null 2>&1; then
                            yum install python-pip3 -y
                        fi
                    fi
                    '''
                }
            }
        }
        stage('prepare-host-mkdir') {
            steps {
                sh '''
                sshpass -p "$server_passwd" ssh -o StrictHostKeyChecking=no "$server_hostname@$server_ip_address" << EOF

                if [ ! -d $REMOTE_SCRIPT_PATH ]; then
                    echo -e "\ncreate path $REMOTE_SCRIPT_PATH"
                    mkdir -p $REMOTE_SCRIPT_PATH
                fi
                cd $REMOTE_SCRIPT_PATH
                pwd
                '''
            }
        }
        stage('prepare-host-upload-script') {
            steps {
                script {
                    sh '''
                    set +e
                    sshpass -p "$server_passwd" scp -r $LOCAL_SCRIPT_PATH* "$server_hostname@$server_ip_address":$REMOTE_SCRIPT_PATH > /dev/null 2>&1
                    
                    sshpass -p "$server_passwd" ssh -o StrictHostKeyChecking=no "$server_hostname@$server_ip_address" << EOF
                    cd $REMOTE_SCRIPT_PATH
                    pwd
                    ./link.sh $code_dir
                    
                    echo "$cherry_picks" > cps 
                    '''
                }
            }
        }
        stage('build') {
            steps {
                sh '''
                devops_token=`cat $DEVOPS_TOKEN_FILE || echo ""`
                
                sshpass -p "$server_passwd" ssh -o StrictHostKeyChecking=no "$server_hostname@$server_ip_address" << EOF
                
                # export devops_token
                echo "devops_token: $devops_token"
                export DEVOPS_TOKEN=$devops_token
                readonly DEVOPS_TOKEN
                
                if [ ! -d "$code_dir" ]; then
                    echo "Project code directory does not exist!!!"
                    exit -1;
                fi
                
                cd "$code_dir"
                echo ""
                echo -------------------------------------------------
                echo code_dir: 
                pwd
                echo -------------------------------------------------
                echo ""
                
                if [ ! -f build.sh ]; then
                    echo "File build.sh does not exist!!!"
                    exit -2;
                fi
                
                if [ $test_pipeline == "true" ]; then
                    echo "Just test pipeline, exit."
                    exit 0
                fi
                bash build.sh "$project_name" "$build_variant" "$build_action" "$build_sign" "$build_verity" "$need_publish" "$devops_host_id" "$devops_compile_id" "$is_new_project" "$test_host" "$BUILD_URL" "$server_ip_address"
                
                '''
            }
        }
        stage('file-upload') {
            steps {
                sh '''
                devops_token=`cat $DEVOPS_TOKEN_FILE || echo ""`
                
                sshpass -p "$server_passwd" ssh -o StrictHostKeyChecking=no "$server_hostname@$server_ip_address" << EOF
                
                # export devops_token
                echo "devops_token: $devops_token"
                export DEVOPS_TOKEN=$devops_token
                readonly DEVOPS_TOKEN
                
                if [ ! -d "$code_dir" ]; then
                    echo "Project code directory does not exist!!!"
                    exit -1;
                fi
                
                cd "$code_dir"
                echo ""
                echo -------------------------------------------------
                echo code_dir: 
                pwd
                echo -------------------------------------------------
                echo ""
                if [ "$build_sign" != "true" ]; then
                    echo -e "\ndo not sign, exit!\n"
                    exit 0
                fi
                
                # upload file
                echo -e '\n./upload_ftp.py -p "$project_name" -h "$sign_ftp_url" -u "$sign_ftp_upload_username" -c "$sign_ftp_upload_passwd"\n'
                python3 upload_ftp.py -p "$project_name" -h "$sign_ftp_url" -u "$sign_ftp_upload_username" -c "$sign_ftp_upload_passwd"
                # if [ "$test_host" == "true" ]; then
                #     echo ftp://hongxiangyuan@192.168.150.30/upload/202104/G1930EPQ_V15_HL/V15-HL-G1930DPQV1HB-ZY-0420-V0103.zip > ftp_url.txt
                # else
                #     python3 upload_ftp.py -p "$project_name" -h "$sign_ftp_url" -u "$sign_ftp_upload_username" -c "$sign_ftp_upload_passwd"
                # fi
                '''
            }
        }
        
        stage('sign-verity') {
            steps {
                sh '''
                devops_token=`cat $DEVOPS_TOKEN_FILE || echo ""`
                
                sshpass -p "$server_passwd" ssh -o StrictHostKeyChecking=no "$server_hostname@$server_ip_address" << EOF
                
                # export devops_token
                echo "devops_token: $devops_token"
                export DEVOPS_TOKEN=$devops_token
                readonly DEVOPS_TOKEN
                
                if [ ! -d "$code_dir" ]; then
                    echo "Project code directory does not exist!!!"
                    exit -1;
                fi
                
                cd "$code_dir"
                echo ""
                echo -------------------------------------------------
                echo code_dir: 
                pwd
                echo -------------------------------------------------
                echo ""
                
                if [ "$build_sign" != "true" ]; then
                    echo -e "\ndo not sign, exit!\n"
                    exit 0
                fi
                
                if [ ! -f sign_verify.sh ]; then
                    echo -e "File sign_verify.sh does not exist!!!"
                    exit -2
                fi
                
                bash sign_verify.sh "$project_name" "$sv_platform_url" "$sv_platform_username" "$sv_platform_passwd" "$sv_platform_terrace" "$sv_platform_board" "$sv_platform_cclist" "$sv_platform_model" "$sv_platform_brand" "$sv_platform_odm" "$publish_username" "$build_verity" "$sv_verity_purpose" "$devops_compile_id"
                '''
            }
        }
    }
    
    post {
        aborted {
            echo 'this build was aborted'
            sh '''
            set +e
            devops_token=`cat $DEVOPS_TOKEN_FILE || echo ""`
            # export devops_token
            echo "devops_token: $devops_token"
            export DEVOPS_TOKEN=$devops_token
            readonly DEVOPS_TOKEN
            
            cd $LOCAL_SCRIPT_PATH
            
            # compile status: 7(stoped)
            echo "./notify_status.py $devops_compile_id task_stopped"
            python3 notify_status.py $devops_compile_id task_stopped
            
            # devops_server server status 0(idle)
            echo "./update_db.py -t devops_server -k server_status -v 0 -w id -e $devops_host_id"
            python3 update_db.py -t devops_server -k server_status -v 0 -w id -e $devops_host_id
            
            # devops_compile finish time
            build_finish_time=`date "+%Y-%m-%d %H:%M:%S"`
            python3 update_db.py -t devops_compile \
                -k compile_build_finish_time -v "$build_finish_time" \
                -w id -e $devops_compile_id
            echo "complete"
            '''
        }
        failure {
            echo 'this build was failed'
            sh '''
            set +e
            devops_token=`cat $DEVOPS_TOKEN_FILE || echo ""`
            # export devops_token
            echo "devops_token: $devops_token"
            export DEVOPS_TOKEN=$devops_token
            readonly DEVOPS_TOKEN
            
            cd $LOCAL_SCRIPT_PATH
            
            # check compile status is 2(init) or 5(compiling)
            python3 notify_status.py $devops_compile_id connecting check
            is_init=$?
            python3 notify_status.py $devops_compile_id compiling check
            is_compiling=$?
            if [ "$is_init" = "3" ] || [ "$is_compiling" = "3" ]; then
                # compile status: 6(build failed)
                echo "./notify_status.py $devops_compile_id build_failed"
                python3 notify_status.py $devops_compile_id build_failed
            fi
            
            # devops_server server status 0(idle)
            echo "./update_db.py -t devops_server -k server_status -v 0 -w id -e $devops_host_id"
            python3 update_db.py -t devops_server -k server_status -v 0 -w id -e $devops_host_id
            echo "complete"
            '''
        }
    }
}