pipeline {
    agent 'any'
    stages {
        stage('prepare') {
            steps {
                script {
                    println "project_name: ${project_name}"
                    println "code_dir: ${code_dir}"
                    println "server_hostname: ${server_hostname}"
                    println "server_ip_address: ${server_ip_address}"
                    println "server_passwd: ${server_passwd}"
                    println "zip_file: ${zip_file}"
                    println "ftp_host: ${ftp_host}"
                    println "ftp_user: ${ftp_user}"
                    println "ftp_user_passwd: ${ftp_user_passwd}"
                }
            }
        }
        stage('prepare-jenkins-server') {
            steps {
                script {
                    sh '''
                    if ! type sshpass >/dev/null 2>&1; then
                        echo -e "\nprepare-jenkins-server: install sshpass"
                        yum install sshpass -y
                    fi
                    if ! type pip >/dev/null 2>&1; then
                        echo -e "\nprepare-jenkins-server: install python-pip"
                        yum install python-pip -y
                    fi
                    '''
                }
            }
        }
        stage('prepare-host-mkdir') {
            steps {
                sh '''
                sshpass -p "$server_passwd" ssh -o StrictHostKeyChecking=no "$server_hostname@$server_ip_address" << EOF

                if [ ! -d "$script_path" ]; then
                    echo -e "\ncreate path $script_path"
                    mkdir -p "$script_path"
                fi
                cd $script_path
                pwd
                '''
            }
        }
        stage('prepare-host-upload-script') {
            steps {
                script {
                    sh '''
                    set +e
                    sshpass -p "$server_passwd" scp -r $script_path "$server_hostname@$server_ip_address":/home/server/.jenkins > /dev/null 2>&1

                    sshpass -p "$server_passwd" ssh -o StrictHostKeyChecking=no "$server_hostname@$server_ip_address" << EOF
                    cd $script_path
                    pwd
                    ./link.sh $code_dir
                    '''
                }
            }
        }
        stage('upload') {
            steps {
                script {
                    sh '''
                    sshpass -p "$server_passwd" ssh -o StrictHostKeyChecking=no "$server_hostname@$server_ip_address" << EOF
                    if [ ! -d "$code_dir" ]; then
                    echo "Project code directory does not exist!!!"
                    exit -1;
                    fi

                    cd "$code_dir"
                    echo ""
                    echo -------------------------------------------------
                    echo code_dir:
                    pwd
                    echo -------------------------------------------------
                    echo ""

                    if [ ! -f upload_ftp.py ]; then
                    echo "File upload_ftp.py does not exist!!!"
                    exit -2;
                    fi

                    echo -e "upload_ftp.py -p $project_name -f $zip_file -i $ftp_host -u $ftp_user -c $ftp_user_passwd"
                    ./upload_ftp.py -p "$project_name" -f "$zip_file" -i "$ftp_host" -u "$ftp_user" -c "$ftp_user_passwd"
                    '''
                }
            }
        }
    }
}